# -*- coding: utf-8 -*-
"""ultimate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQRp1uzHL0vQZtbe6_0QLiNNk1pD20fD

CODES

---
"""

!pip install openai dataclasses python-docx pydantic

"""MAIN"""

from typing import Dict, List, Optional, Set, Union
from dataclasses import dataclass
from enum import Enum
from datetime import datetime
from pydantic import BaseModel, constr, conint
import docx
import json
from openai import OpenAI
import os

class PerformanceEnum(str, Enum):
    GPA = "gpa"
    PERCENTAGE = "percentage"

class SkillLevel(str, Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"

class EmploymentType(str, Enum):
    FREELANCE = "freelance"
    INTERNSHIP = "internship"
    FULLTIME = "full_time"
    PARTTIME = "part_time"

class WorkplaceTypeEnum(str, Enum):
    IN_PERSON = "in_person"
    REMOTE = "remote"
    HYBRID = "hybrid"
    OPEN = "open_to_any"

class JobTypeEnum(str, Enum):
    CONTRACT = "contract"
    INTERNSHIP = "internship"
    PERMANENT = "permanent"

# Data classes for various sections

@dataclass
class SkillResponse:
    name: str = ""
    rating: Optional[int] = None
    versions: Optional[List[str]] = None
    verified_skill_level: Optional[SkillLevel] = None

    def to_dict(self) -> Dict:
        return {
            "name": self.name,
            "rating": self.rating,
            "versions": self.versions,
            "verified_skill_level": (self.verified_skill_level.value
                                       if self.verified_skill_level else None)
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'SkillResponse':
        skill_level = data.get('verified_skill_level')
        if skill_level and not isinstance(skill_level, SkillLevel):
            skill_level = SkillLevel(skill_level)
        return cls(
            name=data.get('name', ''),
            rating=data.get('rating'),
            versions=data.get('versions', []),
            verified_skill_level=skill_level
        )

@dataclass
class JobLocationResponse:
    location_name: str = ""

    def to_dict(self) -> Dict:
        return {
            "location_name": self.location_name
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'JobLocationResponse':
        return cls(location_name=data.get('location_name', ''))

@dataclass
class WorkExperienceResponse:
    work_experience_id: Optional[str] = None
    job_title: Optional[str] = None
    employer: Optional[str] = None
    location: Optional[str] = None
    start_month: Optional[int] = None
    start_year: Optional[int] = None
    end_month: Optional[int] = None
    end_year: Optional[int] = None
    currently_working: Optional[bool] = None
    employment_type: Optional[EmploymentType] = None
    work_description: Optional[str] = None
    work_accomplishment: Optional[str] = None
    work_skills: Optional[List[SkillResponse]] = None
    ctc: Optional[int] = None

    def to_dict(self) -> Dict:
        return {
            "work_experience_id": self.work_experience_id,
            "job_title": self.job_title,
            "employer": self.employer,
            "location": self.location,
            "start_month": self.start_month,
            "start_year": self.start_year,
            "end_month": self.end_month,
            "end_year": self.end_year,
            "currently_working": self.currently_working,
            "employment_type": (self.employment_type.value
                                if self.employment_type else None),
            "work_description": self.work_description,
            "work_accomplishment": self.work_accomplishment,
            "work_skills": [skill.to_dict() for skill in self.work_skills] if self.work_skills else None,
            "ctc": self.ctc
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'WorkExperienceResponse':
        emp_type = data.get('employment_type')
        if emp_type and not isinstance(emp_type, EmploymentType):
            emp_type = EmploymentType(emp_type)
        work_skills = [SkillResponse.from_dict(skill) for skill in data.get('work_skills', [])] if data.get('work_skills') else None
        return cls(
            work_experience_id=data.get('work_experience_id'),
            job_title=data.get('job_title'),
            employer=data.get('employer'),
            location=data.get('location'),
            start_month=data.get('start_month'),
            start_year=data.get('start_year'),
            end_month=data.get('end_month'),
            end_year=data.get('end_year'),
            currently_working=data.get('currently_working'),
            employment_type=emp_type,
            work_description=data.get('work_description'),
            work_accomplishment=data.get('work_accomplishment'),
            work_skills=work_skills,
            ctc=data.get('ctc')
        )

@dataclass
class ProjectResponse:
    title: str = ""
    description: Optional[str] = None
    start_month: Optional[int] = None
    start_year: Optional[int] = None
    end_month: Optional[int] = None
    end_year: Optional[int] = None
    is_in_progress: bool = False

    def to_dict(self) -> Dict:
        return {
            "title": self.title,
            "description": self.description,
            "start_month": self.start_month,
            "start_year": self.start_year,
            "end_month": self.end_month,
            "end_year": self.end_year,
            "is_in_progress": self.is_in_progress
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'ProjectResponse':
        return cls(
            title=data.get('title', ''),
            description=data.get('description'),
            start_month=data.get('start_month'),
            start_year=data.get('start_year'),
            end_month=data.get('end_month'),
            end_year=data.get('end_year'),
            is_in_progress=data.get('is_in_progress', False)
        )

@dataclass
class AchievementResponse:
    title: str = ""
    description: Optional[str] = None

    def to_dict(self) -> Dict:
        return {
            "title": self.title,
            "description": self.description
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'AchievementResponse':
        return cls(
            title=data.get('title', ''),
            description=data.get('description')
        )

@dataclass
class PreferenceResponse:
    job_positions: Optional[Set[str]] = None
    professions: Optional[Set[str]] = None
    industry: Optional[Set[str]] = None
    job_location: Optional[List[JobLocationResponse]] = None
    job_type: Optional[JobTypeEnum] = None
    workplace_type: Optional[WorkplaceTypeEnum] = None
    expected_start_salary: Optional[int] = None
    expected_end_salary: Optional[int] = None
    currency: Optional[str] = None
    open_to_any_location: Optional[bool] = None
    immediate_joining: Optional[bool] = None

    def to_dict(self) -> Dict:
        return {
            "job_positions": list(self.job_positions) if self.job_positions else [],
            "professions": list(self.professions) if self.professions else [],
            "industry": list(self.industry) if self.industry else [],
            "job_location": [loc.to_dict() for loc in self.job_location] if self.job_location else [],
            "job_type": self.job_type.value if self.job_type else None,
            "workplace_type": self.workplace_type.value if self.workplace_type else None,
            "expected_start_salary": self.expected_start_salary,
            "expected_end_salary": self.expected_end_salary,
            "currency": self.currency,
            "open_to_any_location": self.open_to_any_location,
            "immediate_joining": self.immediate_joining
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'PreferenceResponse':
        job_type = data.get('job_type')
        if job_type and not isinstance(job_type, JobTypeEnum):
            job_type = JobTypeEnum(job_type)

        workplace_type = data.get('workplace_type')
        if workplace_type and not isinstance(workplace_type, WorkplaceTypeEnum):
            workplace_type = WorkplaceTypeEnum(workplace_type)

        job_locations = [JobLocationResponse.from_dict(loc) for loc in data.get('job_location', [])] if data.get('job_location') else None
        return cls(
            job_positions=set(data.get('job_positions', [])),
            professions=set(data.get('professions', [])),
            industry=set(data.get('industry', [])),
            job_location=job_locations,
            job_type=job_type,
            workplace_type=workplace_type,
            expected_start_salary=data.get('expected_start_salary'),
            expected_end_salary=data.get('expected_end_salary'),
            currency=data.get('currency'),
            open_to_any_location=data.get('open_to_any_location'),
            immediate_joining=data.get('immediate_joining')
        )


@dataclass
class GapEducation:
    gap_reason: Optional[str] = None
    gap_duration: Optional[int] = None

    def to_dict(self) -> Dict:
        return {
            "gap_reason": self.gap_reason,
            "gap_duration": self.gap_duration
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'GapEducation':
        return cls(
            gap_reason=data.get("gap_reason"),
            gap_duration=data.get("gap_duration")
        )

@dataclass
class EducationsResponse:
    college_name: Optional[str] = None
    degree: Optional[str] = None
    stream: Optional[str] = None
    diploma_board: Optional[str] = None
    course: Optional[str] = None
    enrollment_no: Optional[str] = None
    start_month: Optional[int] = None
    start_year: Optional[int] = None
    end_month: Optional[int] = None
    end_year: Optional[int] = None
    currently_attending: Optional[bool] = None
    performance_scale: Optional[PerformanceEnum] = None
    performance: Optional[float] = None
    skills: Optional[List[SkillResponse]] = None
    achievements: Optional[str] = None
    specialization: Optional[str] = None
    minor_specialization: Optional[str] = None

    def to_dict(self) -> Dict:
        return {
            "college_name": self.college_name,
            "degree": self.degree,
            "stream": self.stream,
            "diploma_board": self.diploma_board,
            "course": self.course,
            "enrollment_no": self.enrollment_no,
            "start_month": self.start_month,
            "start_year": self.start_year,
            "end_month": self.end_month,
            "end_year": self.end_year,
            "currently_attending": self.currently_attending,
            "performance_scale": self.performance_scale.value if self.performance_scale else None,
            "performance": self.performance,
            "skills": [skill.to_dict() for skill in self.skills] if self.skills else None,
            "achievements": self.achievements,
            "specialization": self.specialization,
            "minor_specialization": self.minor_specialization
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'EducationsResponse':
        performance_scale = data.get("performance_scale")
        if performance_scale and not isinstance(performance_scale, PerformanceEnum):
            performance_scale = PerformanceEnum(performance_scale)
        skills = [SkillResponse.from_dict(skill) for skill in data.get("skills", [])] if data.get("skills") else None
        return cls(
            college_name=data.get("college_name"),
            degree=data.get("degree"),
            stream=data.get("stream"),
            diploma_board=data.get("diploma_board"),
            course=data.get("course"),
            enrollment_no=data.get("enrollment_no"),
            start_month=data.get("start_month"),
            start_year=data.get("start_year"),
            end_month=data.get("end_month"),
            end_year=data.get("end_year"),
            currently_attending=data.get("currently_attending"),
            performance_scale=performance_scale,
            performance=data.get("performance"),
            skills=skills,
            achievements=data.get("achievements"),
            specialization=data.get("specialization"),
            minor_specialization=data.get("minor_specialization")
        )

@dataclass
class StudentProfile:
    career_interests: str
    work_experience: List[WorkExperienceResponse]
    projects: List[ProjectResponse]
    skills: List[SkillResponse]
    preferences: PreferenceResponse
    achievements: List[AchievementResponse]
    educations: List[EducationsResponse]
    gap_education: Optional[GapEducation]
    key_takeaways: List[str]  # Changed from str to List[str]
    next_steps: List[str]

    def to_dict(self) -> Dict:
        return {
            "career_interests": self.career_interests,
            "work_experience": [work.to_dict() for work in self.work_experience],
            "projects": [proj.to_dict() for proj in self.projects],
            "skills": [skill.to_dict() for skill in self.skills],
            "preferences": self.preferences.to_dict(),
            "achievements": [achievement.to_dict() for achievement in self.achievements],
            "educations": [edu.to_dict() for edu in self.educations],
            "gap_education": self.gap_education.to_dict() if self.gap_education else None,
            "key_takeaways": self.key_takeaways,
            "next_steps":self.next_steps
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'StudentProfile':
      def convert_to_list(value):
            if isinstance(value, str):
                return [item.strip() for item in value.split('\n') if item.strip()]
            elif isinstance(value, list):
                return value
            return []
      return cls(
            career_interests=data.get('career_interests', ''),
            work_experience=[WorkExperienceResponse.from_dict(work) for work in data.get('work_experience', [])],
            projects=[ProjectResponse.from_dict(proj) for proj in data.get('projects', [])],
            skills=[SkillResponse.from_dict(skill) for skill in data.get('skills', [])],
            preferences=PreferenceResponse.from_dict(data.get('preferences', {})),
            achievements=[AchievementResponse.from_dict(achievement) for achievement in data.get('achievements', [])],
            educations=[EducationsResponse.from_dict(edu) for edu in data.get('educations', [])],
            gap_education=GapEducation.from_dict(data.get('gap_education')) if data.get('gap_education') else None,
            key_takeaways=convert_to_list(data.get('key_takeaways', [])),
            next_steps=convert_to_list(data.get('next_steps', []))
        )

class CareerCounselorAnalyzer:
    def __init__(self, api_key: str):
        self.client = OpenAI(api_key=api_key)

    def _create_extraction_prompt(self, transcript: str) -> str:
      return f"""Given a conversation transcript, extract information into this structured format. Return ONLY the JSON without any additional text or explanation:
{{
    "career_interests": "string",
    "work_experience": [
        {{
            "work_experience_id": "string or null",
            "job_title": "string",
            "employer": "string",
            "location": "string",
            "start_month": integer,
            "start_year": integer,
            "end_month": integer or null,
            "end_year": integer or null,
            "currently_working": boolean,
            "employment_type": "freelance" | "internship" | "full_time" | "part_time",
            "work_description": "string",
            "work_accomplishment": "string",
            "work_skills": [
                {{
                    "name": "string",
                    "rating": integer (1-5),
                    "versions": ["string"],
                    "verified_skill_level": "beginner" | "intermediate" | "advanced"
                }}
            ],
            "ctc": integer or null
        }}
    ],
    "projects": [
        {{
            "title": "string",
            "description": "string",
            "start_month": integer,
            "start_year": integer,
            "end_month": integer or null,
            "end_year": integer or null,
            "is_in_progress": boolean
        }}
    ],
    "skills": [
        {{
            "name": "string",
            "rating": integer (1-5),
            "versions": ["string"],
            "verified_skill_level": "beginner" | "intermediate" | "advanced"
        }}
    ],
    "preferences": {{
        "job_positions": ["string"],
        "professions": ["string"],
        "industry": ["string"],
        "job_location": [
            {{
                "location_name": "string"
            }}
        ],
        "job_type": "contract" | "internship" | "permanent",
        "workplace_type": "in_person" | "remote" | "hybrid" | "open_to_any",
        "expected_start_salary": integer,
        "expected_end_salary": integer,
        "currency": "string",
        "open_to_any_location": boolean,
        "immediate_joining": boolean
    }},
    "achievements": [
        {{
            "title": "string",
            "description": "string"
        }}
    ],
    "educations": [
        {{
            "college_name": "string or null",
            "degree": "string or null",
            "stream": "string or null",
            "diploma_board": "string or null",
            "course": "string or null",
            "enrollment_no": "string or null",
            "start_month": integer,
            "start_year": integer,
            "end_month": integer or null,
            "end_year": integer or null,
            "currently_attending": boolean,
            "performance_scale": "gpa" | "percentage" or null,
            "performance": number or null,
            "skills": [
                {{
                    "name": "string",
                    "rating": integer (1-5),
                    "versions": ["string"],
                    "verified_skill_level": "beginner" | "intermediate" | "advanced"
                }}
            ],
            "achievements": "string or null",
            "specialization": "string or null",
            "minor_specialization": "string or null"
        }}
    ],
    "gap_education": {{
        "gap_reason": "string or null",
        "gap_duration": integer or null
    }},
    "key_takeaways": ["string"],
    "next_steps": ["string"]
}}

NOTE: Strictly adhere to the conversation and do not assume anything and add it to the results.
Extraction rules:
1. Work and Project descriptions should be elaborate, creative and quantified only if mentioned in transcript.
2. Years should be four-digit integers (e.g., 2024)
3. For ongoing activities, omit end_month and end_year and set currently_working or is_in_progress to true
4. Skill ratings should be 1-5 integers. Soft skills should also be compulsorily listed with no verified level.
5. Employment type should match exactly one of the specified values
6. Job type and workplace type should match exactly one of the specified values
7. Currency should be standard 3-letter code (e.g., "USD", "INR")
8. Months should be 1-12 integers.
9. All dates should be in ISO format (YYYY-MM-DD) when possible, or YYYY-MM or YYYY if only partial dates are available.
10. Location should be extracted for institutions, companies when mentioned.
11. If any field is not mentioned in the transcript, use null for optional fields or empty arrays for lists
12. Convert any mentioned CGPAs or Percentages to a 10.0 scale CGPA. No negatives should be entertained and if any, then set to 0.
13. For the key_takeaways field, create a comprehensive detailed report of all important points in the form of an array where each element should be a complete sentence. Each point should:
    - Start with "The student has..." for student information. "The avatar suggested that..."
    - Cover all aspects of the student's profile
    - Must include the avatar's suggestions based on the answer to the question: "Before we wrap up, do you have any questions or topics you’d like to discuss?"
    - Start with "The avatar suggested that..." for avatar's suggestions to the student.
    Include all details about:
    - Educational background and current status with all details.
    - Work experience and roles with all details
    - Skills and expertise levels with all details. This must include soft skills.
    - Career preferences and goals
    - Notable achievements in detail.
    - Any gaps in education/employment and their reasons
    - Avatar's suggestions to the student based on student's questions
    - Any information that is important but is not falling under any of the above category
    Make sure no information is omitted and each point is comprehensive. Make sure every sentence of the conversation that contains important information is included in the report.

14. For the next_steps field, provide comprehensive recommendations as an array where each element should be a detailed suggestion. Structure the recommendations under these categories (each as a separate array element):

    a. Professional Certifications & Training:
    - Industry-Standard Certifications with costs and preparation time
    - Specific online courses from platforms like Coursera, Udemy, edX
    - Professional training programs with timelines

    b. Academic & Research Growth:
    - Relevant upcoming conferences with dates and locations. Keep in mind the current date and suggest accordingly.
    - Research publication opportunities with specific journals. Detail on how and when to register as well.
    - Topics for paper presentations. Give specific titles and topics up to the mark of current industry standards.
    - Guidance on converting projects to research papers

    c. Professional Network Building:
    - Detailed LinkedIn optimization strategy. Atleast 2 sentences with proper steps on how to do the same.
    - Specific industry communities and forums to join. Give proper names if you know any. For example, for a Machine learning student, he could follow Andrew NG.
    - Local meetup groups with details

    d. Project Portfolio Enhancement:
    - At least 2 detailed industry-relevant project suggestions with:
      * Complete project description including name suggestion and what the project is about.
      * Technologies involved including end to end deployment if possible.
      * Learning outcomes
      * USP of each project must be mentioned to make the student stand out.
    - Open source contribution opportunities with specific projects
    - Each project should have the above subheadings: Description, Technologies, Learning Outcomes, USP

    e. Skill Development Roadmap:
    - Priority technical skills with proper learning resources
    - Soft skills development opportunities mentioning why it is important.
    - Timeline for each skill

    f. Career Preparation:
    - Specific job roles matching their profile with required skills
    - Current industry standards for each role
    - Technical interview preparation resources
    - Portfolio presentation strategies

    g. Short-term Action Items (Next 3 Months):
    - Weekly goals for Month 1
    - Key milestones for Months 2-3

    h. Avatar's suggestions based on the answer to the question: "Before we wrap up, do you have any questions or topics you’d like to discuss?"
    - Include the advice the avatar gives when the student asks questions
    - Give a minimum of 4 steps to do the same in proper sentence format

Each recommendation should:
- Be a complete, detailed sentence
- Include specific, actionable steps
- Provide legitimate, verified resources
- Consider budget and time constraints
- Align with industry standards
- Build towards long-term career goals
- Be conversational in tone as if directly advising the student. It should be "You should try..." and so on.

15. For career_interests, consider that the student is in the process of exploring career options.
  - Extract the student's career interests from the following conversation, paying particular attention to their response to the question: "Before we dive in, I’d love to know what brought you here today. Are you exploring opportunities, preparing for a specific goal, or just figuring things out?"
  - Make sure to include proper keywords which can be used to help the student further to find suitable career paths and job roles.
  - Include any aspirations, or other important details as you deem fitbut do not miss out on information.
  - Must include the student's current position, degree, stream or job role - all if all are available for better understanding.

Here's the conversation transcript:
{transcript}"""

    def analyze_transcript(self, transcript: str) -> StudentProfile:
        response = self.client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are an expert career counselor analyst. Extract information in the exact JSON format specified. Include only the JSON in your response, no additional text."},
                {"role": "user", "content": self._create_extraction_prompt(transcript)}
            ],
            temperature=0
        )

        try:
            data = json.loads(response.choices[0].message.content)
            return StudentProfile.from_dict(data)
        except json.JSONDecodeError as e:
            raise ValueError(f"Failed to parse LLM response as JSON: {e}")

def read_transcript(file_path: str) -> str:
    """
    Supports both DOCX and plain text (TXT) formats.
    """
    if file_path.lower().endswith('.docx'):
        try:
            doc = docx.Document(file_path)
            full_text = []
            for paragraph in doc.paragraphs:
                if paragraph.text.strip():
                    full_text.append(paragraph.text)
            return '\n'.join(full_text)
        except Exception as e:
            raise Exception(f"Error reading DOCX file: {str(e)}")
    elif file_path.lower().endswith('.txt'):
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                return f.read()
        except Exception as e:
            raise Exception(f"Error reading TXT file: {str(e)}")
    else:
        raise ValueError("Unsupported file format. Please provide a .docx or .txt file.")

def enhance_descriptions(section: List[Dict], section_type: str, api_key: str, student_skills: List[str] = None) -> List[Dict]:
    """
    Enhances descriptions for work experience or projects while ensuring strict adherence to original content
    and incorporating relevant student skills.

    Args:
        section: List of work/project items to enhance
        section_type: Type of section ("work" or "project")
        api_key: OpenAI API key
        student_skills: List of all skills the student has (optional)

    Returns:
        List of enhanced items with improved descriptions
    """
    enhanced_section = []
    llm_client = OpenAI(api_key=api_key)

    def format_skills_context(skills: List[str]) -> str:
        if not skills:
            return ""
        return (
            "Consider incorporating these verified skills where they genuinely match the "
            f"experience (only if explicitly relevant): {', '.join(skills)}. "
            "Do not force or assume skill usage if not clearly indicated in the original content."
        )

    for item in section:
        # Extract item-specific skills
        item_skills = []
        if section_type == "work":
            item_skills = [skill.get('name', '') for skill in (item.get('work_skills') or [])]
            details = (
                f"Original Job Details:\n"
                f"- Job Title: {item.get('job_title', '')}\n"
                f"- Original Description: {item.get('work_description', '')}\n"
                f"- Documented Accomplishments: {item.get('work_accomplishment', '')}\n"
                f"- Verified Skills Used: {', '.join(item_skills)}"
            )
        else:
            details = (
                f"Original Project Details:\n"
                f"- Project Title: {item.get('title', '')}\n"
                f"- Original Description: {item.get('description', '')}"
            )

        # Combine item-specific skills with overall student skills
        all_relevant_skills = list(set(item_skills + (student_skills or [])))

        prompt = f"""Task: Enhance the following {section_type} description with these strict requirements:

1. STRICT RULES:
   - Only use information explicitly stated in the original content
   - Do not make assumptions or add information not present
   - Do not infer responsibilities or achievements not directly mentioned
   - Keep the same level of specificity as the original

2. FORMAT:
   - Generate 2-3 bullet points
   - Each bullet should start with a strong action verb
   - Separate bullets with newlines
   - Do not include headers or titles

3. CONTENT FOCUS:
   - Emphasize specific responsibilities and concrete achievements
   - Highlight measurable impacts when explicitly stated
   - Include technologies/tools only if specifically mentioned
   - Quantify metrics if mentioned in input else strictly just enhance the description without assuming or adding anything extra.

{format_skills_context(all_relevant_skills)}

{details}

Enhanced Description:"""

        response = llm_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": (
                    "You are a precise resume enhancer that strictly adheres to original content. "
                    "Never add assumed information. Only enhance what is explicitly stated."
                )},
                {"role": "user", "content": prompt}
            ],
            temperature=0.1
        )

        enhanced_text = response.choices[0].message.content.strip()

        if section_type == "work":
            item["work_description"] = enhanced_text
        else:
            item["description"] = enhanced_text

        enhanced_section.append(item)

    return enhanced_section

def enhance_next_steps(profile: StudentProfile, api_key: str) -> List[str]:
    """
    Enhances next steps recommendations while maintaining the structured format
    and adding more specific, actionable details.

    Args:
        profile: Complete StudentProfile object containing work, education, projects, and current next steps
        api_key: OpenAI API key

    Returns:
        List of enhanced next step recommendations
    """
    llm_client = OpenAI(api_key=api_key)

    # Prepare context from profile
    context = {
        "current_education": [edu.to_dict() for edu in profile.educations],
        "work_experience": [work.to_dict() for work in profile.work_experience],
        "projects": [proj.to_dict() for proj in profile.projects],
        "skills": [skill.to_dict() for skill in profile.skills],
        "current_next_steps": profile.next_steps
    }

    prompt = f"""Based on the current_next_steps from the context, provide enhanced next steps recommendations. Consider elements from student's profile while enhancing.
Format your response as a list of recommendations, with each recommendation on a new line starting with "- ".

Current Profile Context:
{json.dumps(context, indent=2)}

Maintain the structure of the recommendations and simply enhance it making sure the headers are present followed by the recommendations:

a. Professional Certifications & Training:
- Industry-Standard Certifications with costs and preparation time
- Specific online courses from platforms like Coursera, Udemy, edX
- Professional training programs with timelines

b. Academic & Research Growth:
- Relevant upcoming conferences with dates and locations (current date: {datetime.now().strftime('%B %Y')})
- Research publication opportunities with specific journals and registration details
- Specific paper presentation topics matching current industry standards
- Guidance on converting projects to research papers

c. Professional Network Building:
- Detailed LinkedIn optimization strategy (minimum 2 sentences)
- Specific industry communities and forums to join, including notable people to follow
- Local meetup groups with details

d. Project Portfolio Enhancement:
- Include atleast 2 project names with complete description, overview, name suggestion, full tech stack, learning outcomes, and a cool USP
- Technologies involved including end to end deployment if possible

Also include:
- Open source contribution opportunities with specific projects

e. Skill Development Roadmap:
- Priority technical skills with specific learning resources
- Soft skills development opportunities with importance explained
- Timeline for each skill

f. Career Preparation:
- Specific job roles matching their profile with required skills
- Current industry standards for each role
- Technical interview preparation resources
- Portfolio presentation strategies

g. Short-term Action Items (Next 3 Months):
- Weekly goals for Month 1
- Key milestones for Months 2-3

h. All of avatar's suggestions based on the answer to the question: "Before we wrap up, do you have any questions or topics you’d like to discuss?"

Each recommendation must:
- Be conversational ("You should try...", "Consider exploring...")
- Include specific action steps
- Name actual resources and tools
- Consider realistic timelines and budgets
- Align with industry trends
- Focus on long-term career growth

Return ONLY the list of recommendations, with each starting with "- "."""

    response = llm_client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": (
                "You are a career advisor who provides highly specific, actionable advice. "
                "Focus on concrete details, real resources, and clear steps."
            )},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3
    )

    try:
        # Split response into individual recommendations
        recommendations = [
            line.strip()[2:].strip()  # Remove "- " prefix and extra whitespace
            for line in response.choices[0].message.content.split('\n')
            if line.strip().startswith('- ')
        ]

        # Validate we have enough recommendations
        if len(recommendations) < 10:  # Arbitrary minimum number of recommendations
            raise ValueError("Insufficient number of recommendations generated")

        return recommendations

    except Exception as e:
        print(f"Error processing next steps enhancement: {str(e)}")
        # Return original next steps if enhancement fails
        return profile.next_steps

def main():
    # Configuration
    transcript_file = '/content/new-conversation.txt' #PASS ON THE TRANSCRIPT
    API_KEY = 'sk-KEY'
    output_file = "analysis_results.json"

    try:
        # Step 1: Read and analyze transcript
        print("Reading transcript file...")
        transcript = read_transcript(transcript_file)
        print("Transcript content:")
        print(transcript)
        print("\nAnalyzing transcript...")

        analyzer = CareerCounselorAnalyzer(api_key=API_KEY)
        profile = analyzer.analyze_transcript(transcript)

        # Get skills from profile
        student_skills = [skill.name for skill in profile.skills] if profile.skills else []

        # Enhance work experience descriptions
        print("\nEnhancing work experience descriptions...")
        work_experience_list = [we.to_dict() for we in profile.work_experience]
        enhanced_work = enhance_descriptions(
            section=work_experience_list,
            section_type="work",
            api_key=API_KEY,
            student_skills=student_skills
        )
        profile.work_experience = [WorkExperienceResponse.from_dict(item) for item in enhanced_work]

        # Enhance project descriptions
        print("\nEnhancing project descriptions...")
        projects_list = [proj.to_dict() for proj in profile.projects]
        enhanced_projects = enhance_descriptions(
            section=projects_list,
            section_type="project",
            api_key=API_KEY,
            student_skills=student_skills
        )
        profile.projects = [ProjectResponse.from_dict(item) for item in enhanced_projects]

        # Enhance next steps
        print("\nEnhancing next steps recommendations...")
        enhanced_next_steps = enhance_next_steps(profile, API_KEY)
        profile.next_steps = enhanced_next_steps

        # Save results
        print("\nSaving enhanced profile...")
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(profile.to_dict(), f, indent=4, ensure_ascii=False)
        print(f"Results saved to {output_file}")

    except Exception as e:
        print(f"An error occurred: {str(e)}")
        raise

if __name__ == "__main__":
    main()